apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.samplecontroller.reshnm.de
spec:
  group: samplecontroller.reshnm.de
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
            status:
              type: object
              properties:
                podName:
                  type: string

  names:
    kind: MyResource
    plural: myresources
  scope: Namespaced
