apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-sample-controller-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-sample-controller-crd
subjects:
  - kind: ServiceAccount
    name: k8s-sample-controller-crd
    namespace: {{ .Values.namespace }}